name: Workflow for Ruby code coverage
on: [push, pull_request]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Ruby latest
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.0.2'
            - name: Set up Database
              run: bin/rails db:migrate RAILS_ENV=test
            - name: Install dependencies
              run: bundle install
            - name: Run tests and collect coverage
              run: bundle exec rake
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3